### ISSUE TITLE
[Bancheck]  local variable 'member_avatar_url' referenced before assignment

### ISSUE THREAD

**Issue by Brandjuh** [PhasecoreX/PCXCogs#15]
When I try to ban a member by ID I will get the following error:

```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/bancheck/bancheck.py", line 568, in banreport
    await self._user_report(ctx, proof_image_url, True, member, ban_message)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/bancheck/bancheck.py", line 697, in _user_report
    member_avatar_url,
UnboundLocalError: local variable 'member_avatar_url' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'member_avatar_url' referenced before assignment

```
![image](https://user-images.githubusercontent.com/26203955/81802416-5371af80-9516-11ea-9de0-a618fca2fa77.png)

**Comment by PhasecoreX** [comment]
Sorry about that, should be fixed now!
