### ISSUE TITLE
Discord.services Down

### ISSUE THREAD

**Issue by PhasecoreX** [PhasecoreX/PCXCogs#2]
Looks like https://discord.services is down, so auto ban checks will fail silently. I need to set up an error handler (it's returning a 521 web server is down error), and should also look into adding other public ban lists as failovers.

Here's the stack trace:
```
Traceback (most recent call last):
  File "/data/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/bancheck/bancheck.py", line 72, in search
    await self.user_lookup(ctx.channel, member)
  File "/data/cogs/CogManager/cogs/bancheck/bancheck.py", line 83, in user_lookup
    response = await self.lookup(member.id)
  File "/data/cogs/CogManager/cogs/bancheck/bancheck.py", line 117, in lookup
    result = await response.json()
  File "/data/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1027, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 912, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 512, in invoke
    await super().invoke(ctx)
  File "/data/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1065, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/data/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 639, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
```

**Comment by PhasecoreX** [comment]
f0b4f4e fixes this (at least it doesn't cause a stack trace anymore). I still need to add more ban list sources though, since currently the plugin is kind of useless.
