### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pelathaon** [PhasecoreX/PCXCogs#25]
Traceback (most recent call last):
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/redbot/.local/share/Red-DiscordBot/data/Elemental/cogs/CogManager/cogs/autoroom/autoroom.py", line 290, in on_voice_state_update
    await self._process_autoroom_delete(member.guild, auto_voice_channels)
  File "/home/redbot/.local/share/Red-DiscordBot/data/Elemental/cogs/CogManager/cogs/autoroom/autoroom.py", line 344, in _process_autoroom_delete
    for vc in guild.get_channel(category_id).voice_channels:
AttributeError: 'NoneType' object has no attribute 'voice_channels'

**Comment by PhasecoreX** [comment]
Did you end up removing the category that your AutoRoom source was pointing at?

I'll need to add some error handling regardless.

**Comment by PhasecoreX** [comment]
Added some stale config cleanup logic, as well as a display of all configured AutoRooms in 65f8105. Hopefully this fixes any future issues that would have come up. Thanks for the bug report!
