### ISSUE TITLE
NetSpeed bug

### ISSUE THREAD

**Issue by vertyco** [PhasecoreX/PCXCogs#41]
When i run [p]netspeed i get this traceback error.

Traceback (most recent call last):
  File "C:\Users\Admin\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\VertyBot\cogs\CogManager\cogs\netspeed\netspeed.py", line 31, in netspeed
    s = speedtest.Speedtest(secure=True)
  File "C:\Users\Admin\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\VertyBot\cogs\Downloader\lib\speedtest.py", line 1091, in __init__
    self.get_config()
  File "C:\Users\Admin\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\VertyBot\cogs\Downloader\lib\speedtest.py", line 1173, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\redenv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Admin\redenv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Admin\redenv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 10: ''

**Comment by PhasecoreX** [comment]
So I think 1c01947 fixes this. After 2 years of working the package this is based on (`speedtest-cli`) had an update a day ago to fix this underlying issue. Updating the cog will update this package too, its just that for some reason I think you also have to restart the bot afterwards.
