### ISSUE TITLE
[Autoroom] Error in "Autoroom allow"

### ISSUE THREAD

**Issue by Zenchaeus** [PhasecoreX/PCXCogs#43]
When I try to use the command "autoroom allow" there's always an error. It worked before but when I tried earlier it no longer worked. I provided the traceback results below.

Exception in command 'autoroom allow'
Traceback (most recent call last):
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/mkurisu069/.local/share/Red-DiscordBot/data/Redbot/cogs/CogManager/cogs/autoroom/commands/autoroom.py", line 109, in allow
    await self._process_allow_deny(ctx, True, member_or_role=member_or_role)
  File "/home/mkurisu069/.local/share/Red-DiscordBot/data/Redbot/cogs/CogManager/cogs/autoroom/commands/autoroom.py", line 139, in _process_allow_deny
    if not await self.check_required_perms(ctx.guild):
AttributeError: 'AutoRoom' object has no attribute 'check_required_perms'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/mkurisu069/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'AutoRoom' object has no attribute 'check_required_perms'

**Comment by PhasecoreX** [comment]
Make sure you've updated the cog. I fixed this yesterday.

**Comment by Zenchaeus** [comment]
> Make sure you've updated the cog. I fixed this yesterday.

i'll try to update now and will get back after

**Comment by Zenchaeus** [comment]
it works fine now. thanks!
