### ISSUE TITLE
[remindme] error on `forgetme`

### ISSUE THREAD

**Issue by maxbooiii** [PhasecoreX/PCXCogs#61]
Ran into an error on `forgetme`, seems to happen only if you don't type any number after `forgetme`. 

```py
Traceback (most recent call last):
  File "/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/redbot/cogs/CogManager/cogs/remindme/c_reminder.py", line 236, in forgetme
    await self._delete_reminder(ctx, "all")
  File "/root/redbot/cogs/CogManager/cogs/remindme/c_reminder.py", line 341, in _delete_reminder
    await self.update_bg_task(author.id)
  File "/root/redbot/cogs/CogManager/cogs/remindme/remindme.py", line 624, in update_bg_task
    user_reminder_id = int(user_reminder_id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by PhasecoreX** [comment]
Should be fixed now, update and let me know if it's not!
