### ISSUE TITLE
An unexpected exception occurred in the background loop of UpdateNotify. Updates will not be checked until UpdateNotify is reloaded.

### ISSUE THREAD

**Issue by axlroden** [PhasecoreX/PCXCogs#82]
Got this msg today, checked the logs:
```bash
[2022-06-10 14:29:46] [ERROR] red.pcxcogs.updatenotify: Unexpected exception occurred in background loop of UpdateNotify:
Traceback (most recent call last):
  File "/data/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 106, in error_handler
    fut.result()
  File "/data/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 134, in bg_loop
    await self.check_for_updates()
  File "/data/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 141, in check_for_updates
    message = await self.update_check()
  File "/data/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 350, in update_check
    latest_redbot_version = await self.get_latest_redbot_version()
  File "/data/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 300, in get_latest_redbot_version
    async with session.get(url) as resp:
  File "/data/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/data/venv/lib/python3.9/site-packages/aiohttp/client.py", line 570, in _request
    raise TooManyRedirects(
aiohttp.client_exceptions.TooManyRedirects: 0, message='', url=URL('https://pypi.org/pypi/Red-DiscordBot/json')
```

Tried wget'in this url:

```bash
wget https://pypi.org/pypi/Red-DiscordBot/json
--2022-06-10 12:41:46--  https://pypi.org/pypi/Red-DiscordBot/json
Resolving pypi.org (pypi.org)... 151.101.0.223, 151.101.128.223, 151.101.64.223, ...
Connecting to pypi.org (pypi.org)|151.101.0.223|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
--2022-06-10 12:41:47--  https://pypi.org/pypi/Red-DiscordBot/json
Reusing existing connection to pypi.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://pypi.org/pypi/Red-DiscordBot/json [following]
20 redirections exceeded.
```

**Comment by PhasecoreX** [comment]
Is this still happening? I tried the wget command and it worked fine, as well as the cog itself is working. PyPi may have had some glitch for a moment.

**Comment by axlroden** [comment]
Nope problem seems to have resolved.
