### ISSUE TITLE
An unexpected exception occurred in the background loop of UpdateNotify.

### ISSUE THREAD

**Issue by PureLoneWolf** [PhasecoreX/PCXCogs#94]
Hi there

I noticed a little while ago that updatenotify wasn't pinging me, but only after bouncing my server did the bot start messaging me with the error:

> An unexpected exception occurred in the background loop of UpdateNotify.
> Updates will not be checked until UpdateNotify is reloaded.
> Check your console or logs for details, and consider opening a bug report for this.

Looking at the logs, I see this:

`[2022-10-14 17:52:19] [ERROR] red.pcxcogs.updatenotify: Unexpected exception occurred in background loop of UpdateNotify: 
Traceback (most recent call last):
  File "/home/wolflan/.local/share/Red-DiscordBot/data/Nymeria/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 106, in error_handler
    fut.result()
  File "/home/wolflan/.local/share/Red-DiscordBot/data/Nymeria/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 134, in bg_loop
    await self.check_for_updates()
  File "/home/wolflan/.local/share/Red-DiscordBot/data/Nymeria/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 143, in check_for_updates
    message = await self.update_check()
  File "/home/wolflan/.local/share/Red-DiscordBot/data/Nymeria/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 357, in update_check
    latest_redbot_version = await self.get_latest_redbot_version()
  File "/home/wolflan/.local/share/Red-DiscordBot/data/Nymeria/cogs/CogManager/cogs/updatenotify/updatenotify.py", line 304, in get_latest_redbot_version
    async with session.get(url) as resp:
  File "/home/wolflan/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/wolflan/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/wolflan/redenv/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError`

I saw someone else (Issue 82 I think), but that one seemed to resolve itself.  Unfortunately not the case for me.

I'm not sure what I can do here, so any help would be appreciated :)

Many thanks

**Comment by PhasecoreX** [comment]
That's a timeout error when the cog is calling out to https://pypi.org/pypi/Red-DiscordBot/json in order to check the current redbot version. I am able to connect to it just fine, so not really sure what could be causing that issue. Can you go to that page? Do you have some sort of firewall preventing redbot from hitting that page?

**Comment by PureLoneWolf** [comment]
Nope - It's on a Linux box in a data center and there is no firewall configured or enabled.

I don't have a browser available, but I can ping pypi.org without issue

**Comment by PhasecoreX** [comment]
Hopefully! Yeah every time I've tried to enable IPv6 on my network or on servers it never goes well. I'd love for it to just work but there's always some weird edge case.
